### ISSUE TITLE
Firefox issue with fieldsets

### ISSUE THREAD

**Issue by jonmak08** [liferay/lexicon#138]
Firefox has some awkward fieldset styling involving `width` that interferes with the responsive table. This cannot be overriden without a Firefox-specific hack that is not provided in Bootstrap:

```css
@-moz-document url-prefix() {
  fieldset { display: table-cell; }
}
```
For more information, read https://stackoverflow.com/questions/17408815/fieldset-resizes-wrong-appears-to-have-unremovable-min-width-min-content/17863685#17863685

For Bootstrap's documentation, see http://getbootstrap.com/css/#callout-tables-responsive-ff-fieldset
